### ISSUE TITLE
[home-assistant] Homeassistant fails to start with AppDaemon enabled

### ISSUE THREAD

**Issue by rwlove** [k8s-at-home/charts#10]
**Describe the bug**
I'm instantiating HASS in a kubernetes cluster using the following definition. https://github.com/billimek/billimek-charts/tree/master/charts/home-assistant
 
Homeassistant fails to start with AppDaemon enabled.

**A clear and concise description of what the bug is.**
Version of Helm and Kubernetes:
Helm: v3.2.1
Kubernetes: v1.18.2

What happened:
```
➜  kubernetes git:(master) ✗ kubectl -n homeassistant logs homeassistant-home-assistant-8ccc9d79-f22bk -c appdaemon 
2020-06-14 16:35:45.284536 INFO AppDaemon Version 3.0.5 starting
2020-06-14 16:35:45.284770 INFO Configuration read from: /conf/appdaemon.yaml
2020-06-14 16:35:45.286422 INFO AppDaemon: Starting Apps
2020-06-14 16:35:45.289228 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2020-06-14 16:35:45.329504 INFO AppDaemon: HASS: HASS Plugin Initializing
2020-06-14 16:35:45.329869 INFO AppDaemon: HASS: HASS Plugin initialization complete
2020-06-14 16:35:45.330040 INFO Starting Dashboards
2020-06-14 16:35:45.330182 WARNING ------------------------------------------------------------
2020-06-14 16:35:45.330251 WARNING Unexpected error during run()
2020-06-14 16:35:45.330311 WARNING ------------------------------------------------------------
2020-06-14 16:35:45.330992 WARNING Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/appdaemon/admain.py", line 82, in run
    self.rundash = rundash.RunDash(self.AD, loop, self.logger, self.access, **hadashboard)
  File "/usr/local/lib/python3.6/site-packages/appdaemon/rundash.py", line 130, in __init__
    dash_net = url.netloc.split(":")
TypeError: a bytes-like object is required, not 'str'

2020-06-14 16:35:45.331065 WARNING ------------------------------------------------------------
2020-06-14 16:35:45.331140 INFO AppDeamon Exited
```

Relevant Configuration Section
```
appdaemon:
  enabled: true

  ## code-server container image                                                                                                              
  ##                                                                                                                                          
  image:
    repository: acockburn/appdaemon
    tag: 3.0.5
    pullPolicy: IfNotPresent

  ## Home Assistant API token                                                                                                                 
  # haToken:                                                                                                                                  

  ## Additional hass-vscode container environment variable                                                                                    
  ## For instance to add a http_proxy                                                                                                         
  ##                                                                                                                                          
  extraEnv: {}

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx                                                                                                    
      # kubernetes.io/tls-acme: "true"                                                                                                        
    path: /
    hosts:
      - appdaemon.local
    tls: []
    #  - secretName: appdaemon-tls                                                                                                            
    #    hosts:                                                                                                                               
    #      - appdaemon.local

  service:
    type: ClusterIP
    port: 5050
    annotations: {}                                                                                                                           
    labels: {}                                                                                                                                
    clusterIP: ""
    ## List of IP addresses at which the hass-appdaemon service is available                                                                  
    ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips                                                                      
    ##                                                                                                                                        
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    # nodePort: 30000
```

**Comment by xeor** [comment]
I don't use ingress, and is hitting this same problem. However, it looks like https://github.com/k8s-at-home/charts/blob/master/charts/home-assistant/values.yaml#L300 the `appdaemon.extraEnv` is never used..? Is it being used somewhere else? It is missing from https://github.com/k8s-at-home/charts/blob/master/charts/home-assistant/templates/deployment.yaml

**Comment by lexfrei** [comment]
Welp, here is a typo https://github.com/k8s-at-home/charts/blob/44fbca1fb807e995cce77e22995f96c270ea1ebf/charts/home-assistant/templates/deployment.yaml#L368

I'm working on PR with a fix for this issue and some other improvements.

**Comment by lexfrei** [comment]
@xeor now you can set any envs you need (at least, for appdaemon)

**Comment by onedr0p** [comment]
Looks like this issue can be closed because the environment variables should be working for appdaemon :D
